/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesCodePlayRouteImport } from './routes/games/$code/play'
import { Route as GamesCodeLobbyRouteImport } from './routes/games/$code/lobby'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCodePlayRoute = GamesCodePlayRouteImport.update({
  id: '/games/$code/play',
  path: '/games/$code/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCodeLobbyRoute = GamesCodeLobbyRouteImport.update({
  id: '/games/$code/lobby',
  path: '/games/$code/lobby',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/games/$code/play': typeof GamesCodePlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/games/$code/play': typeof GamesCodePlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/games/$code/play': typeof GamesCodePlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/join'
    | '/games/$code/lobby'
    | '/games/$code/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/join' | '/games/$code/lobby' | '/games/$code/play'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/join'
    | '/games/$code/lobby'
    | '/games/$code/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  GamesCodeLobbyRoute: typeof GamesCodeLobbyRoute
  GamesCodePlayRoute: typeof GamesCodePlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$code/play': {
      id: '/games/$code/play'
      path: '/games/$code/play'
      fullPath: '/games/$code/play'
      preLoaderRoute: typeof GamesCodePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$code/lobby': {
      id: '/games/$code/lobby'
      path: '/games/$code/lobby'
      fullPath: '/games/$code/lobby'
      preLoaderRoute: typeof GamesCodeLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  GamesCodeLobbyRoute: GamesCodeLobbyRoute,
  GamesCodePlayRoute: GamesCodePlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
